/**
 * Scans ./assets for the production media the edit expects and writes
 * src/asset-manifest.ts — a static map of {assetKey: exists}. Components read
 * this synchronously to decide between real footage and a placeholder slate.
 *
 * Runs automatically before `npm run dev` / `render` (see package.json pre*
 * hooks), so dropping files into assets/ and re-running picks them up.
 */
import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const assetsDir = join(root, "assets");

const EXPECTED = [
  ...Array.from({ length: 10 }, (_, i) => `live/shot-${String(i + 1).padStart(2, "0")}.mp4`),
  ...Array.from({ length: 12 }, (_, i) => `screen/rec-${String(i + 1).padStart(2, "0")}.mp4`),
  "vo/master.mp3",
  "vo/agents.mp3",
  "vo/developers.mp3",
  "vo/communities.mp3",
  "vo/master.json",
  "vo/agents.json",
  "vo/developers.json",
  "vo/communities.json",
  "music/bed.mp3",
];

const manifest = {};
for (const key of EXPECTED) {
  manifest[key] = existsSync(join(assetsDir, key));
}

const present = Object.values(manifest).filter(Boolean).length;
const body = `/**
 * AUTO-GENERATED by scripts/scan-assets.mjs — do not edit by hand.
 * ${present}/${EXPECTED.length} expected assets present at last scan.
 */
export const ASSET_MANIFEST: Record<string, boolean> = ${JSON.stringify(manifest, null, 2)};

/** True when the given staticFile-relative asset path exists on disk. */
export const hasAsset = (key: string): boolean => ASSET_MANIFEST[key] === true;
`;

const outPath = join(root, "src", "asset-manifest.ts");
mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, body);
console.log(`[scan-assets] ${present}/${EXPECTED.length} assets present -> ${outPath}`);
