/**
 * AUTO-GENERATED by scripts/scan-assets.mjs — do not edit by hand.
 * 0/31 expected assets present at last scan.
 */
export const ASSET_MANIFEST: Record<string, boolean> = {
  "live/shot-01.mp4": false,
  "live/shot-02.mp4": false,
  "live/shot-03.mp4": false,
  "live/shot-04.mp4": false,
  "live/shot-05.mp4": false,
  "live/shot-06.mp4": false,
  "live/shot-07.mp4": false,
  "live/shot-08.mp4": false,
  "live/shot-09.mp4": false,
  "live/shot-10.mp4": false,
  "screen/rec-01.mp4": false,
  "screen/rec-02.mp4": false,
  "screen/rec-03.mp4": false,
  "screen/rec-04.mp4": false,
  "screen/rec-05.mp4": false,
  "screen/rec-06.mp4": false,
  "screen/rec-07.mp4": false,
  "screen/rec-08.mp4": false,
  "screen/rec-09.mp4": false,
  "screen/rec-10.mp4": false,
  "screen/rec-11.mp4": false,
  "screen/rec-12.mp4": false,
  "vo/master.mp3": false,
  "vo/agents.mp3": false,
  "vo/developers.mp3": false,
  "vo/communities.mp3": false,
  "vo/master.json": false,
  "vo/agents.json": false,
  "vo/developers.json": false,
  "vo/communities.json": false,
  "music/bed.mp3": false
};

/** True when the given staticFile-relative asset path exists on disk. */
export const hasAsset = (key: string): boolean => ASSET_MANIFEST[key] === true;
